name: reminder
description: Reminder mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_local_notifications: ^17.0.0
  flutter_timezone: ^5.1.0
  timezone: ^0.9.2
  intl: ^0.18.1
  shared_preferences: ^2.5.3
  fl_chart: ^1.0.0
  pdf: ^3.11.0
  printing: ^5.13.4
  http: ^1.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
